# API to dataframe

In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg',
   'genre_ids': [16, 28, 12, 18],
   'id': 1560520,
   'title': 'Batman: Knightfall Part 1: Knightfall',
   'original_language': 'en',
   'original_title': 'Batman: Knightfall Part 1: Knightfall',
   'overview': 'Arkham Asylum has been destroyed, and all its inmates have been unleashed upon Gotham City. As Batman races to round up some of his greatest enemies, he is pushed to his physical and mental limits and into a final confrontation with a new threat: the man called Bane!',
   'popularity': 35.3018,
   'poster_path': '/360qdtu2hLnqMu8SVHMywn420w1.jpg',
   'release_date': '2026-06-23',
   'softcore': False,
   'video': False,
   'vote_average': 9.1,
   'vote_count': 483},
  {'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 12, 14, 28],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 65.2271,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.038,
   'vote_count': 1381},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 41.3127,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.848,
   'vote_count': 2269},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 12.6812,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.823,
   'vote_count': 403},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 46.4911,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.8,
   'vote_count': 2343},
  {'adult': False,
   'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg',
   'genre_ids': [80, 28, 53],
   'id': 1621552,
   'title': 'Facing El Chapo',
   'original_language': 'es',
   'original_title': 'La captura',
   'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.',
   'popularity': 36.6887,
   'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg',
   'release_date': '2026-08-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.787,
   'vote_count': 963},
  {'adult': False,
   'backdrop_path': '/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 58.5755,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.734,
   'vote_count': 31684},
  {'adult': False,
   'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 54.7724,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.689,
   'vote_count': 23854},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 559.3291,
   'poster_path': '/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.634,
   'vote_count': 8536},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 13.5127,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.601,
   'vote_count': 333},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 47.949,
   'poster_path': '/dueFqKLvjftnELZaGYwY7xinfaI.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.598,
   'vote_count': 4629},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 29.972,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.576,
   'vote_count': 10530},
  {'adult': False,
   'backdrop_path': '/pGzqRKrYeK4LogoysNro0vG8d8N.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 34.5036,
   'poster_path': '/8a1lJs7mFyGhGhZZDT1azJUoQiZ.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.572,
   'vote_count': 14524},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 38.089,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 18105},
  {'adult': False,
   'backdrop_path': '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg',
   'genre_ids': [28, 18, 10749],
   'id': 1630423,
   'title': 'My Dearest Assassin',
   'original_language': 'th',
   'original_title': 'เลือดรักนักฆ่า',
   'overview': 'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.',
   'popularity': 15.9747,
   'poster_path': '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg',
   'release_date': '2026-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 314},
  {'adult': False,
   'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 30.9712,
   'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.542,
   'vote_count': 1260},
  {'adult': False,
   'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
   'genre_ids': [28, 53, 80],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 56.0453,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.539,
   'vote_count': 37091},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 51.2824,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.536,
   'vote_count': 19120},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 35.1911,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 20039},
  {'adult': False,
   'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 49.1476,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.505,
   'vote_count': 27675}],
 'total_pages': 568,
 'total_results': 11348}

In [4]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg',
  'genre_ids': [16, 28, 12, 18],
  'id': 1560520,
  'title': 'Batman: Knightfall Part 1: Knightfall',
  'original_language': 'en',
  'original_title': 'Batman: Knightfall Part 1: Knightfall',
  'overview': 'Arkham Asylum has been destroyed, and all its inmates have been unleashed upon Gotham City. As Batman races to round up some of his greatest enemies, he is pushed to his physical and mental limits and into a final confrontation with a new threat: the man called Bane!',
  'popularity': 35.3018,
  'poster_path': '/360qdtu2hLnqMu8SVHMywn420w1.jpg',
  'release_date': '2026-06-23',
  'softcore': False,
  'video': False,
  'vote_average': 9.1,
  'vote_count': 483},
 {'adult': False,
  'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
  'genre_ids': [16, 12, 14, 28],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 65.2271,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.038,
  'vote_count': 1381},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 41.3127,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.848,
  'vote_count': 2269},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 12.6812,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.823,
  'vote_count': 403},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 46.4911,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.8,
  'vote_count': 2343},
 {'adult': False,
  'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg',
  'genre_ids': [80, 28, 53],
  'id': 1621552,
  'title': 'Facing El Chapo',
  'original_language': 'es',
  'original_title': 'La captura',
  'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.',
  'popularity': 36.6887,
  'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg',
  'release_date': '2026-08-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.787,
  'vote_count': 963},
 {'adult': False,
  'backdrop_path': '/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 58.5755,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.734,
  'vote_count': 31684},
 {'adult': False,
  'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 54.7724,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.689,
  'vote_count': 23854},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 559.3291,
  'poster_path': '/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.634,
  'vote_count': 8536},
 {'adult': False,
  'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
  'genre_ids': [18, 10749],
  'id': 1232449,
  'title': 'Young Hearts',
  'original_language': 'nl',
  'original_title': 'Young Hearts',
  'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
  'popularity': 13.5127,
  'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
  'release_date': '2024-10-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.601,
  'vote_count': 333},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 47.949,
  'poster_path': '/dueFqKLvjftnELZaGYwY7xinfaI.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.598,
  'vote_count': 4629},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 29.972,
  'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.576,
  'vote_count': 10530},
 {'adult': False,
  'backdrop_path': '/pGzqRKrYeK4LogoysNro0vG8d8N.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 34.5036,
  'poster_path': '/8a1lJs7mFyGhGhZZDT1azJUoQiZ.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.572,
  'vote_count': 14524},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 38.089,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 18105},
 {'adult': False,
  'backdrop_path': '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg',
  'genre_ids': [28, 18, 10749],
  'id': 1630423,
  'title': 'My Dearest Assassin',
  'original_language': 'th',
  'original_title': 'เลือดรักนักฆ่า',
  'overview': 'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.',
  'popularity': 15.9747,
  'poster_path': '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg',
  'release_date': '2026-05-06',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 314},
 {'adult': False,
  'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 30.9712,
  'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.542,
  'vote_count': 1260},
 {'adult': False,
  'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
  'genre_ids': [28, 53, 80],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 56.0453,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.539,
  'vote_count': 37091},
 {'adult': False,
  'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 51.2824,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.536,
  'vote_count': 19120},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 35.1911,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 20039},
 {'adult': False,
  'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 49.1476,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.505,
  'vote_count': 27675}]

In [10]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [11]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,35.3018,9.100,483
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,65.2271,9.038,1381
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,41.3127,8.848,2269
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.6812,8.823,403
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,46.4911,8.800,2343

In [13]:
df.shape

(0, 0)

In [25]:
frames = [df]

for i in range(1, 429):
    response = requests.get(
        'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(
            i)
    )
    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']
    ]
    frames.append(temp_df)
df = pd.concat(frames, ignore_index=True)

In [26]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,9.8686,8.500,4635
1,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,35.7757,8.492,13141
2,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-04,76.5230,8.492,41653
3,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,41.9537,8.489,21579
4,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,39.5514,8.481,31184
...,...,...,...,...,...,...,...
17095,9268,Eraser,"Eraser, an elite federal marshal who ""erases"" ...",1996-06-21,8.5637,6.108,2143
17096,829410,Sick,While quarantining at her family's lake house ...,2022-09-11,3.8440,6.106,391
17097,291356,In a Valley of Violence,The story of a drifter named Paul who arrives ...,2016-10-21,3.6260,6.104,658
17098,14636,The Condemned,Jack Conrad is awaiting the death penalty in a...,2007-04-27,4.9306,6.100,913
17099,12412,Miracle at St. Anna,Miracle at St. Anna chronicles the story of fo...,2008-09-15,3.0000,6.104,408

In [34]:
df.shape

(17100, 7)

In [36]:
df.to_csv('data/movies.csv')

# Working with csv files

In [37]:
df = pd.read_csv('data/aug_train.csv')

In [38]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

Opening a csv file from an URL

In [43]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers = headers)
req

In [44]:
req.text

'Country,Region\rAlgeria,AFRICA\rAngola,AFRICA\rBenin,AFRICA\rBotswana,AFRICA\rBurkina,AFRICA\rBurundi,AFRICA\rCameroon,AFRICA\rCape Verde,AFRICA\rCentral African Republic,AFRICA\rChad,AFRICA\rComoros,AFRICA\rCongo,AFRICA\r"Congo, Democratic Republic of",AFRICA\rDjibouti,AFRICA\rEgypt,AFRICA\rEquatorial Guinea,AFRICA\rEritrea,AFRICA\rEthiopia,AFRICA\rGabon,AFRICA\rGambia,AFRICA\rGhana,AFRICA\rGuinea,AFRICA\rGuinea-Bissau,AFRICA\rIvory Coast,AFRICA\rKenya,AFRICA\rLesotho,AFRICA\rLiberia,AFRICA\rLibya,AFRICA\rMadagascar,AFRICA\rMalawi,AFRICA\rMali,AFRICA\rMauritania,AFRICA\rMauritius,AFRICA\rMorocco,AFRICA\rMozambique,AFRICA\rNamibia,AFRICA\rNiger,AFRICA\rNigeria,AFRICA\rRwanda,AFRICA\rSao Tome and Principe,AFRICA\rSenegal,AFRICA\rSeychelles,AFRICA\rSierra Leone,AFRICA\rSomalia,AFRICA\rSouth Africa,AFRICA\rSouth Sudan,AFRICA\rSudan,AFRICA\rSwaziland,AFRICA\rTanzania,AFRICA\rTogo,AFRICA\rTunisia,AFRICA\rUganda,AFRICA\rZambia,AFRICA\rZimbabwe,AFRICA\rAfghanistan,ASIA\rBahrain,ASIA\rBangladesh,ASIA\rBhutan,ASIA\rBrunei,ASIA\rBurma,ASIA\rCambodia,ASIA\rChina,ASIA\rEast Timor,ASIA\rIndia,ASIA\rIndonesia,ASIA\rIran,ASIA\rIraq,ASIA\rIsrael,ASIA\rJapan,ASIA\rJordan,ASIA\rKazakhstan,ASIA\r"Korea, North",ASIA\r"Korea, South",ASIA\rKuwait,ASIA\rKyrgyzstan,ASIA\rLaos,ASIA\rLebanon,ASIA\rMalaysia,ASIA\rMaldives,ASIA\rMongolia,ASIA\rNepal,ASIA\rOman,ASIA\rPakistan,ASIA\rPhilippines,ASIA\rQatar,ASIA\rRussian Federation,ASIA\rSaudi Arabia,ASIA\rSingapore,ASIA\rSri Lanka,ASIA\rSyria,ASIA\rTajikistan,ASIA\rThailand,ASIA\rTurkey,ASIA\rTurkmenistan,ASIA\rUnited Arab Emirates,ASIA\rUzbekistan,ASIA\rVietnam,ASIA\rYemen,ASIA\rAlbania,EUROPE\rAndorra,EUROPE\rArmenia,EUROPE\rAustria,EUROPE\rAzerbaijan,EUROPE\rBelarus,EUROPE\rBelgium,EUROPE\rBosnia and Herzegovina,EUROPE\rBulgaria,EUROPE\rCroatia,EUROPE\rCyprus,EUROPE\rCzech Republic,EUROPE\rDenmark,EUROPE\rEstonia,EUROPE\rFinland,EUROPE\rFrance,EUROPE\rGeorgia,EUROPE\rGermany,EUROPE\rGreece,EUROPE\rHungary,EUROPE\rIceland,EUROPE\rIreland,EUROPE\rItaly,EUROPE\rLatvia,EUROPE\rLiechtenstein,EUROPE\rLithuania,EUROPE\rLuxembourg,EUROPE\rMacedonia,EUROPE\rMalta,EUROPE\rMoldova,EUROPE\rMonaco,EUROPE\rMontenegro,EUROPE\rNetherlands,EUROPE\rNorway,EUROPE\rPoland,EUROPE\rPortugal,EUROPE\rRomania,EUROPE\rSan Marino,EUROPE\rSerbia,EUROPE\rSlovakia,EUROPE\rSlovenia,EUROPE\rSpain,EUROPE\rSweden,EUROPE\rSwitzerland,EUROPE\rUkraine,EUROPE\rUnited Kingdom,EUROPE\rVatican City,EUROPE\rAntigua and Barbuda,NORTH AMERICA\rBahamas,NORTH AMERICA\rBarbados,NORTH AMERICA\rBelize,NORTH AMERICA\rCanada,NORTH AMERICA\rCosta Rica,NORTH AMERICA\rCuba,NORTH AMERICA\rDominica,NORTH AMERICA\rDominican Republic,NORTH AMERICA\rEl Salvador,NORTH AMERICA\rGrenada,NORTH AMERICA\rGuatemala,NORTH AMERICA\rHaiti,NORTH AMERICA\rHonduras,NORTH AMERICA\rJamaica,NORTH AMERICA\rMexico,NORTH AMERICA\rNicaragua,NORTH AMERICA\rPanama,NORTH AMERICA\rSaint Kitts and Nevis,NORTH AMERICA\rSaint Lucia,NORTH AMERICA\rSaint Vincent and the Grenadines,NORTH AMERICA\rTrinidad and Tobago,NORTH AMERICA\rUnited States,NORTH AMERICA\rAustralia,OCEANIA\rFiji,OCEANIA\rKiribati,OCEANIA\rMarshall Islands,OCEANIA\rMicronesia,OCEANIA\rNauru,OCEANIA\rNew Zealand,OCEANIA\rPalau,OCEANIA\rPapua New Guinea,OCEANIA\rSamoa,OCEANIA\rSolomon Islands,OCEANIA\rTonga,OCEANIA\rTuvalu,OCEANIA\rVanuatu,OCEANIA\rArgentina,SOUTH AMERICA\rBolivia,SOUTH AMERICA\rBrazil,SOUTH AMERICA\rChile,SOUTH AMERICA\rColombia,SOUTH AMERICA\rEcuador,SOUTH AMERICA\rGuyana,SOUTH AMERICA\rParaguay,SOUTH AMERICA\rPeru,SOUTH AMERICA\rSuriname,SOUTH AMERICA\rUruguay,SOUTH AMERICA\rVenezuela,SOUTH AMERICA'

In [45]:
data = StringIO(req.text)
data

In [46]:
pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

Sep parameter

Genrally the use of pd.read_csv

`pandas.read_csv
pandas.read_csv(filepath_or_buffer, *, sep=<no_default>, delimiter=<no_default>, header='infer', names=<no_default>, index_col=None, usecols=None, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, skip_blank_lines=True, parse_dates=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=<no_default>)`